"""create electricity_providers table

Revision ID: 04394844ac34
Revises: f5b8995cc0ba
Create Date: 2022-01-29 22:34:23.041707

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04394844ac34'
down_revision = 'f5b8995cc0ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('electricity_providers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('logo', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('price_kwh', sa.REAL(), nullable=False),
    sa.Column('mininum_limit_kwh', sa.REAL(), nullable=False),
    sa.Column('number_of_clients', sa.Integer(), nullable=False),
    sa.Column('average_rating', sa.REAL(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('electricity_providers')
    # ### end Alembic commands ###
