"""empty message

Revision ID: 7c9e36079bd9
Revises: 
Create Date: 2022-01-30 00:44:33.226959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c9e36079bd9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('electricity_providers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('logo', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('price_kwh', sa.REAL(), nullable=False),
    sa.Column('mininum_limit_kwh', sa.REAL(), nullable=False),
    sa.Column('number_of_clients', sa.Integer(), nullable=False),
    sa.Column('average_rating', sa.REAL(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('False', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('electricity_providers')
    # ### end Alembic commands ###
