class KeysTypeError(Exception):
    ...

class KeysMissing(Exception):
    ...

class ToManyKeys(Exception):
    ...

class EmailAlreadyExists(Exception):
    ...

class UserNotFound(Exception):
    ...

class UserNotAuthorized(Exception):
    ...